db:
#  conn_str: "root:123@/test?charset=utf8"

web:
  address: ":8080"

log:
  level: "info"
  accessLogfile: "log/access.log"
  runtimeLogfile: "log/runtime.log"

# 精确到秒
job:
#  jobname:
#    cron: "* * * * * *"

jenkins:
  address: "http://172.16.2.88:8080"
  token:  "118f677d3e8596a6bde966ca5f57c2d018"