db:
  conn_str: "sre_tool_wr_all:VNBpFpUSjdxFj6jfSpwN@(hc-business-mw01-mysql.ttpai.top:3306)/ares?charset=utf8mb4&loc=Asia%2FShanghai"

web:
  address: ":8080"

log:
  level: "info"
  accessLogfile: "/opt/logs/app/access.log"
  runtimeLogfile: "/opt/logs/app/runtime.log"

# 精确到秒
job:
  taskManager:
    cron: "@every 10s"
#  jobname:
#    cron: "* * * * * *"

jenkins:
  address: "http://172.16.2.88:8080"
  token:  "118f677d3e8596a6bde966ca5f57c2d018"
  username: "admin"
  password: "hello@ttpai"

k8s:
  clusters:
    dev:
      name: "k8s-k6-dev"
      config_path: "config/k6-cluster-config"
      description: "开发环境K6集群"
    test:
      name: "k8s-k2-test" 
      config_path: "config/k2-cluster-config"
      description: "测试环境K2集群"
    moni:
      name: "k8s-k2-moni"
      config_path: "config/k2-cluster-config" 
      description: "模拟环境K2集群"

