// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/apps": {
            "post": {
                "tags": [
                    "App"
                ],
                "summary": "创建单应用",
                "parameters": [
                    {
                        "description": "创建单应用参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.CreateAppRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "$ref": "#/definitions/app.CreateAppResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/apps/batch": {
            "post": {
                "tags": [
                    "App"
                ],
                "summary": "批量创建应用",
                "parameters": [
                    {
                        "description": "批量创建应用参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.CreateAppsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "$ref": "#/definitions/app.CreateAppsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/apps/name/{app_name}": {
            "get": {
                "description": "根据应用名称获取单个应用的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App"
                ],
                "summary": "根据名称获取应用详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "应用名称",
                        "name": "app_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "$ref": "#/definitions/entity.Apps"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "应用不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/apps/query": {
            "post": {
                "description": "支持多条件组合查询应用列表，包括应用ID、应用名称、开发语言、负责人等",
                "tags": [
                    "App"
                ],
                "summary": "查询应用列表",
                "parameters": [
                    {
                        "description": "应用查询参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.AppQuery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "$ref": "#/definitions/app.AppQueryResult"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/apps/{app_id}": {
            "get": {
                "description": "根据应用ID获取单个应用的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "App"
                ],
                "summary": "根据ID获取应用详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "应用ID",
                        "name": "app_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "$ref": "#/definitions/entity.Apps"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "应用不存在",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/deploy/publish": {
            "post": {
                "tags": [
                    "Publish"
                ],
                "summary": "单应用进行发布动作",
                "parameters": [
                    {
                        "description": "发布请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/publish.CreatePublishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "$ref": "#/definitions/entity.TaskRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/deploy/publish/batch": {
            "post": {
                "tags": [
                    "Publish"
                ],
                "summary": "应用进行批量发布动作",
                "parameters": [
                    {
                        "description": "发布请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/publish.CreateBatchPublishRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "$ref": "#/definitions/publish.CreateBatchPublishResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/deploy/publish/jobs/status": {
            "get": {
                "tags": [
                    "Publish"
                ],
                "summary": "获取任务构建列表",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "$ref": "#/definitions/entity.TaskRecord"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/deploy/query/status": {
            "get": {
                "tags": [
                    "Publish"
                ],
                "summary": "获取构建任务的状态",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "调用链异常",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/job/log/": {
            "get": {
                "tags": [
                    "Publish"
                ],
                "summary": "获取流式的构建日志",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "调用链异常",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/status/nodes": {
            "get": {
                "tags": [
                    "Jenkins"
                ],
                "summary": "获取jenkins节点的状态",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/jenkins.Node"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "内部错误",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "502": {
                        "description": "调用链异常",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/home": {
            "get": {
                "tags": [
                    "Health"
                ],
                "summary": "健康检测",
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/util.ResponseTemplate"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "code": {
                                            "type": "integer"
                                        },
                                        "result": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.AppQuery": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "integer"
                },
                "app_name": {
                    "type": "string"
                },
                "dev_language": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "owner_cn": {
                    "type": "string"
                },
                "page_num": {
                    "type": "integer",
                    "minimum": 1
                },
                "page_size": {
                    "description": "前端可选 15 30 50 100 200",
                    "type": "integer",
                    "maximum": 200,
                    "minimum": 1
                },
                "sort": {
                    "$ref": "#/definitions/util.SortOption"
                }
            }
        },
        "app.AppQueryResult": {
            "type": "object",
            "properties": {
                "apps": {
                    "description": "应用列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Apps"
                    }
                },
                "page_num": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "page_size": {
                    "description": "每页大小",
                    "type": "integer"
                },
                "total": {
                    "description": "总记录数",
                    "type": "integer"
                },
                "total_pages": {
                    "description": "总页数",
                    "type": "integer"
                }
            }
        },
        "app.CreateAppRequest": {
            "type": "object",
            "properties": {
                "app_name": {
                    "type": "string"
                },
                "app_name_cn": {
                    "type": "string"
                },
                "description_cn": {
                    "type": "string"
                },
                "dev_language": {
                    "type": "string"
                },
                "git_url": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "owner_cn": {
                    "type": "string"
                }
            }
        },
        "app.CreateAppResult": {
            "type": "object",
            "properties": {
                "app": {
                    "$ref": "#/definitions/entity.Apps"
                },
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "app.CreateAppsRequest": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.CreateAppRequest"
                    }
                }
            }
        },
        "app.CreateAppsResponse": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/app.CreateAppResult"
                    }
                },
                "failure_count": {
                    "description": "失败数量",
                    "type": "integer"
                },
                "success_count": {
                    "description": "成功数量",
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "entity.Apps": {
            "type": "object",
            "properties": {
                "app_id": {
                    "type": "integer"
                },
                "app_name": {
                    "type": "string"
                },
                "app_name_cn": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "deleted_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "description_cn": {
                    "type": "string"
                },
                "dev_language": {
                    "type": "string"
                },
                "git_url": {
                    "type": "string"
                },
                "owner": {
                    "type": "string"
                },
                "owner_cn": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "entity.TaskRecord": {
            "type": "object",
            "properties": {
                "app_name": {
                    "type": "string"
                },
                "auto_deploy": {
                    "type": "integer"
                },
                "branch": {
                    "type": "string"
                },
                "cd_build_id": {
                    "type": "integer"
                },
                "cd_job_name": {
                    "type": "string"
                },
                "ci_build_id": {
                    "type": "integer"
                },
                "ci_job_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "deleted_at": {
                    "type": "string",
                    "format": "date-time"
                },
                "message": {
                    "type": "string"
                },
                "pipeline_param": {
                    "type": "string"
                },
                "products": {
                    "type": "string"
                },
                "publisher": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string",
                    "format": "date-time"
                }
            }
        },
        "jenkins.Node": {
            "type": "object",
            "properties": {
                "node_name": {
                    "type": "string"
                },
                "node_status": {
                    "type": "string"
                }
            }
        },
        "publish.CreateBatchPublishRequest": {
            "type": "object",
            "properties": {
                "batch_publish": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/publish.CreatePublishRequest"
                    }
                }
            }
        },
        "publish.CreateBatchPublishResponse": {
            "type": "object",
            "properties": {
                "failure_count": {
                    "description": "失败数量",
                    "type": "integer"
                },
                "success_count": {
                    "description": "成功数量",
                    "type": "integer"
                },
                "task_records": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/publish.CreatePublishResult"
                    }
                },
                "total_count": {
                    "description": "总体数量",
                    "type": "integer"
                }
            }
        },
        "publish.CreatePublishRequest": {
            "type": "object",
            "properties": {
                "app_name": {
                    "type": "string"
                },
                "branch": {
                    "type": "string"
                },
                "env": {
                    "type": "string"
                },
                "publisher": {
                    "type": "string"
                }
            }
        },
        "publish.CreatePublishResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "task_record": {
                    "$ref": "#/definitions/entity.TaskRecord"
                }
            }
        },
        "util.ResponseTemplate": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "此处约定：1代表成功，0代表失败",
                    "type": "integer"
                },
                "error": {
                    "description": "如果请求失败，这里一定要给出错误的信息"
                },
                "help": {
                    "description": "显示接口文档地址，便于别人排错",
                    "type": "string"
                },
                "msg": {
                    "description": "对请求结果的描述消息，可以为空",
                    "type": "string"
                },
                "result": {
                    "description": "如果请求成功，这里给出成功的结果"
                }
            }
        },
        "util.SortOption": {
            "type": "object",
            "properties": {
                "direction": {
                    "description": "排序方向：asc/desc",
                    "type": "string"
                },
                "field": {
                    "description": "排序字段",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
